= Step 8: Upload Distribution Staging

== Description

Finally create a directory with release name ({revnumber} in this example) in https://dist.apache.org/repos/dist/dev/fineract and add the following files in this new directory:

* apache-fineract-bin-{revnumber}.tar.gz
* apache-fineract-bin-{revnumber}.tar.gz.sha512
* apache-fineract-bin-{revnumber}.tar.gz.asc
* apache-fineract-src-{revnumber}.tar.gz
* apache-fineract-src-{revnumber}.tar.gz.sha512
* apache-fineract-src-{revnumber}.tar.gz.asc

These files (or "artifacts") make up the release candidate.

Upload these files to ASF's distribution dev (staging) area:

[source,bash,subs="attributes+"]
----
svn mkdir https://dist.apache.org/repos/dist/dev/fineract/{revnumber}
svn checkout https://dist.apache.org/repos/dist/dev/fineract/{revnumber}
cp path/to/files/* {revnumber}/
cd {revnumber}/
svn add * && svn commit
----

NOTE: You will need your ASF Committer credentials to be able to access the Subversion host at `dist.apache.org`.

== Gradle Task

.Command
[source,bash,subs="attributes+,+macros"]
----
./gradlew fineractReleaseStep8 -Pfineract.release.version={revnumber}
----

CAUTION: This task is inefficient. Follow `svn mkdir` and other manual steps above.
